export const LOAD_REPOS = 'LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_FAIL = 'LOAD_REPOS_FAIL';
export const LOAD_MORE_REPOS_SUCCESS = 'LOAD_MORE_REPOS_SUCCESS';
export const LOAD_STARGAZERS = 'LOAD_STARGAZERS';
export const LOAD_STARGAZERS_SUCCESS = 'LOAD_STARGAZERS_SUCCESS';
export const LOAD_STARGAZERS_FAIL = 'LOAD_STARGAZERS_FAIL';
